module.exports = {
  PRATILIPI_ID:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  TITLE:			{ type: 'STRING',    mode: 'NULLABLE' },
  TITLE_EN:			{ type: 'STRING',    mode: 'NULLABLE' },
  LANGUAGE:			{ type: 'STRING',    mode: 'REQUIRED' },
  AUTHOR_ID:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  SUMMARY:			{ type: 'STRING',    mode: 'NULLABLE' },
  PRATILIPI_TYPE:		{ type: 'STRING',    mode: 'REQUIRED' },
  CONTENT_TYPE:			{ type: 'STRING',    mode: 'REQUIRED' },
  STATE:			{ type: 'STRING',    mode: 'REQUIRED' },
  COVER_IMAGE:			{ type: 'BOOLEAN',   mode: 'REQUIRED' },
  LISTING_DATE:			{ type: 'TIMESTAMP', mode: 'REQUIRED' },
  LAST_UPDATED:			{ type: 'TIMESTAMP', mode: 'REQUIRED' },
  WORD_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  IMAGE_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  PAGE_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  CHAPTER_COUNT:		{ type: 'INTEGER',   mode: 'REQUIRED' },
  REVIEW_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  RATING_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  TOTAL_RATING:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  READ_COUNT_OFFSET:		{ type: 'INTEGER',   mode: 'REQUIRED' },
  READ_COUNT:			{ type: 'INTEGER',   mode: 'REQUIRED' },
  FB_LIKE_SHARE_COUNT_OFFSET:	{ type: 'INTEGER',   mode: 'REQUIRED' },
  FB_LIKE_SHARE_COUNT:		{ type: 'INTEGER',   mode: 'REQUIRED' },
  _TIMESTAMP_: 			{ type: 'TIMESTAMP', mode: 'REQUIRED' }
};
